spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/personal_financial"
        username: root
        password:
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
        jackson:
            deserialization:
                fail-on-unknown-properties: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: khoree602@gmail.com
        password: zgrdzlxwqbfhepri
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true