spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/personal_financial"
        username: root
        password:
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
        jackson:
            deserialization:
                fail-on-unknown-properties: true